### ISSUE TITLE
Typo on https://docs.pydantic.dev/latest/usage/pydantic_settings/#adding-sources

### ISSUE THREAD

**Issue by kkirsche** [pydantic/site-feedback#2]
```
    def get_field_value(
        self, field: FieldInfo, field_name: str
    ) -> Tuple[Any, str, bool]:
        encoding = self.config.get('env_file_encoding')
        file_content_json = json.loads(
            Path('tests/example_test_config.json').read_text(encoding)
        )
        fiel_value = file_content_json.get(field_name)
        return fiel_value, field_name, False
```

has a typo of `fiel_value` instead of `field_value`

**Comment by hramezani** [comment]
Thanks @kkirsche for reporting this 🙏 

This is not the right place to report this. There is a specific repo for [pydantic-settings](https://github.com/pydantic/pydantic-settings). you can find the docs there.

I close this issue here.

Please open a PR on `pydantic-settings` repo and fix the typo. Otherwise, I can fix it.

**Comment by kkirsche** [comment]
Sorry about that, I had searched in pydantic/pydantic and forgot about the new split. That's on me, sorry again

**Comment by hramezani** [comment]
@kkirsche No worries.
